### ISSUE TITLE
[Releases]: Tag annotation not fetched; release job cannot trigger

### ISSUE THREAD

**Issue by Kangie** [chromium-linux-tarballs/chromium-tarballs#16]
The CI is supposed to use the tag annotation and extract the correct variable from that. This works if I run `git pull` to fetch CI created tags, or clone a fresh copy of the repo:

```console
kangie@monolith /tmp $ git clone git@github.com:chromium-linux-tarballs/chromium-tarballs.git
Cloning into 'chromium-tarballs'...
...
Resolving deltas: 100% (98/98), done.                                                            
kangie@monolith /tmp $ cd chromium-tarballs     
kangie@monolith /tmp/chromium-tarballs (master) $ git tag -l --format='%(contents:subject)' 133.0.6888.2 | awk '{ print $3 }'
dev
```

This same command retrieves the commit message instead of the annotation in CI:

https://github.com/chromium-linux-tarballs/chromium-tarballs/blob/5374d61c69eced10e84bed0b889b4c6e8ba38d42/.github/workflows/tarballs.yml#L52

```
374d61 (grafted, HEAD -> master, tag: 133.0.6888.2, tag: 132.0.6834.46, origin/master, origin/HEAD) create release: tarball names start with 'chromium'
```

```console
13/12   chromium-notifs  New release: Chromium 133.0.6888.2: dev (December 12, 2024 at 04:12 UTC)
02:53   chromium-notifs  Successfully generated Chromium tarballs for 133.0.6888.2 (tarball)                                                                                                                                                                                        
02:59   chromium-notifs  Successfully uploaded Chromium tarballs for 133.0.6888.2 (tarball)  
```

I suspect that the checkout-v4 action is to blame, we may have to resort to calling `git` directly to ensure that this info is fetched. Even a shallow clone tests fine locally.

Before I do that @iskunk, do you have any thoughts?

**Comment by iskunk** [comment]
The `checkout@v4` action doesn't get the annotations, even with `fetch-depth: 0`? (By default, it gets no history nor tags.)

Calling `git` directly is no big deal if not, just not a measure I've typically seen needed in cases like this. (If you wanted to download a non-GitHub Git repo, then that's another story, of course)

**Comment by Kangie** [comment]
> The `checkout@v4` action doesn't get the annotations, even with `fetch-depth: 0`? (By default, it gets no history nor tags.)

That seems to be what we're seeing. The workflow only runs on tags, and we use the tag name in the notifications, but no annotation. It's not the end of the world, just frustrating that we have to jump through hoops to use information I'd expect to be available with `fetch-depth 0`.

> Calling `git` directly is no big deal if not, just not a measure I've typically seen needed in cases like this. (If you wanted to download a non-GitHub Git repo, then that's another story, of course)

Let's see if we can get away with a `fetch`?

**Comment by Kangie** [comment]
Well that worked, and the workflow ran automatically while I was in the car so let's call this one solved. :)
