### ISSUE TITLE
Adding the GN source code to the tarball?

### ISSUE THREAD

**Issue by refi64** [chromium-linux-tarballs/chromium-tarballs#2]
First off: thank you so much for hosting these, I had to switch Flathub Chromium over because of the issues with the official ones :sweat_smile: 

I understand that part of the goal with these tarballs is to be smaller than the official ones. That being said, I was wondering if you'd be willing to accept a PR that adds the GN source code to them? It would make it possible to follow a pretty typical bootstrapping flow, and the addition would be rather small (a few megabytes).

**Comment by Kangie** [comment]
Sure. We use a system GN over in Gentoo-land but I have no objections to including it in the tarball. If you know the steps already I'll let you submit a PR to include it - it's pretty tiny overall.

**Comment by iskunk** [comment]
I'd like to see GN in there for two reasons:
1. The official tarball has it. It's fine for this tarball to leave out things we don't need, but IMO what is present should match what Google has. (IOW, that this tarball is a strict subset of theirs.)
   ```
   $ ls chromium-130.0.6723.116-upstream/tools/gn
   AUTHORS  OWNERS     bootstrap/  docs/      infra/  roll_gn.py*  tools/
   LICENSE  README.md  build/      examples/  misc/   src/         tutorial/
   $ ls chromium-130.0.6723.116-gentoo/tools/gn
   README.md  bootstrap/  roll_gn.py*  tutorial/
   ```
2. The ungoogled-chromium project uses the bundled GN to do their build (since the source typically requires a bleeding-edge version), and they're not alone in that.

Do you know the correct post-checkout hook invocation to populate that directory as upstream has it?

**Comment by Kangie** [comment]
> Do you know the correct post-checkout hook invocation to populate that directory as upstream has it?

No, I was waiting on a PR from @refi64 assuming that they knew. Upstream are working on their CI now, so we can probably crib their notes from a run that succeeded.

The upstream CI recipe probably contains the magic: https://chromium.googlesource.com/chromium/tools/build/+/refs/heads/main/recipes/recipe_modules/chromium/

**Comment by iskunk** [comment]
I barely know my way around Google's Chromium automation, and I suspect @refi64 is in the same boat :-]

Do you know where the log files for previous Google tarball generations can be found? I think that may be a better starting point... the Git repo would be the second thing to look at.

**Comment by Kangie** [comment]
Here's the actual CI job that's not delivering tarballs currently, we can work backwards from that to find the actual script / LUCI stuff for that pipeline. Otherwise we can go back to find a job that actually succeeded and check the steps - there's probably a `GN` step later in the process?

I honestly assumed that gclient was taking care of that.

**Comment by Kangie** [comment]
This looks like a good example:

https://ci.chromium.org/ui/p/infra/builders/cron/publish_tarball/b8730805095345299521/overview

**Comment by iskunk** [comment]
Thanks for the link! Are you getting this error anytime you try clicking on a stdout/stderr file?

`ERROR: start fetch: rpc error: code = NotFound desc = stream path not found`

**Comment by Kangie** [comment]
Yes, unfortunately. I guess we're going to need to track down the recipe!

This looks like it, complete with some ongoing work to fix the broken CI due to Rust:

https://chromium.googlesource.com/chromium/tools/build/+/refs/heads/main/recipes/recipes/publish_tarball.py

**Comment by refi64** [comment]
Oh I did find out how this works already, was mostly just waiting for some time to uhh download another copy of the source tree lol (which I did start downloading today...).

**Comment by iskunk** [comment]
> Yes, unfortunately. I guess we're going to need to track down the recipe!
> 
> This looks like it, complete with some ongoing work to fix the broken CI due to Rust:
> 
> https://chromium.googlesource.com/chromium/tools/build/+/refs/heads/main/recipes/recipes/publish_tarball.py
> 
> This is where GN steps start. It would be worth ensuring that we aren't missing anything else important (on the other hand our tarballs already build so...)

Ooh, good find! I see the V8 PGO profile bit in there, and GN stuff starts happening at line 582. Looking through this now.
